### ISSUE TITLE
sessionstore chokes on latest itsdangerous

### ISSUE THREAD

**Issue by cshields** [mcrowson/flask-sessionstore#31]
Looks like itsdangerous was [changed 10 days ago](https://github.com/pallets/itsdangerous/commit/0635526a8291da42aa0055a8207d7afe85154830), and does not import properly for flask-sessionstore (flask is set to pull itsdangerous>=0.24).

```
>>> from flask_sessionstore import Session
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib64/python3.6/site-packages/flask_sessionstore/__init__.py", line 16, in <module>
    from .sessions import NullSessionInterface, RedisSessionInterface, \
  File "/usr/local/lib64/python3.6/site-packages/flask_sessionstore/sessions.py", line 19, in <module>
    from itsdangerous import Signer, BadSignature, want_bytes
ImportError: cannot import name 'want_bytes'
```

**Comment by mcrowson** [comment]
Hey thanks. Due to lack of time and need in the community i had stopped maintaining this project.
